### ISSUE TITLE
New .pnp file format and bulk file upload

### ISSUE THREAD

**Issue by ThreadPitt** [SharePoint/PnP-Sites-Core#1435]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ x] SharePoint 2016
[ ] SharePoint 2013

When using a bulk file upload together with the new .pnp file format, where do I have to put the source files, e.g. in my example the folder "**MyDocs**" with its corresponding files?
In the .pnp file itself or in the folder where the .pnp file is stored?
If in the .pnp file, in which folder?

I debugged thru the code and it seems like the engine looks in the .pnp file, but still no files were uploaded...!?

	<pnp:Files>
		<pnp:Directory Src="**.\MyDocs**"
		Folder="NewDocs"
		Overwrite="true"
		Recursive="true"
		IncludedExtensions="*.docx,*.png"
		ExcludedExtensions="*.xml" />
	</pnp:Files>

Any hint is appreciated!
Thx!

**Comment by erwinvanhunen** [comment]
I fixed the issue with the cmdlet. To add a file to an existing PnP file you can simply do:

Add-PnPFileToProvisioningTemplate -Path yourtemplate.pnp -Source ./path/to/your/file.png -Folder "TargetFolderInTheSite".

The update to this cmdlet will be available in the upcoming December 2017 release. I will close this issue, but do not hesitate to reopen it in case you have more questions/issues.

**Comment by ThreadPitt** [comment]
Thanks Erwin,
in the meantime, I already implemented my own "import/export" solution without the PnP engine, but I'll keep that in mind

**Comment by martinjgreen** [comment]
This seems to be still broken - complains about missing URI, but looking at the source there is no argument or variable called URI, nor does any of the documentation refer to it.
