### ISSUE TITLE
Apply-SPOProvisioningTemplate command failing for non existing pages.

### ISSUE THREAD

**Issue by PieterVeenstra** [SharePoint/PnP-Sites-Core#414]
The Apply template command is giving me the following error when I am applying a template which includes a page that doesn't yet exist.

*_PS C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE> Apply-SPOProvisioningTemplate -Path C:\Data\WebTemplates\template.xml -Web /group
[ERROR] Apply-SPOProvisioningTemplate : Value cannot be null.
[ERROR] Parameter name: stream
[ERROR] At line:1 char:1
[ERROR] + Apply-SPOProvisioningTemplate -Path C:...
[ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], ArgumentNullException
[ERROR]     + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate
[ERROR]  
*_

This could happen when you go through the following steps:
1. create a site
2. rename the default page to something else or set the welcome page to a new page
3. get the provisioning template
4. apply the template to the new site.

**Comment by PaoloPia** [comment]
Hi Pieter,
I think is issue has been fixed a while ago. Can you confirm? Thanks.

**Comment by PaoloPia** [comment]
Hi Pieter,
I just double-checked the described scenario and as far as I can see it works. Thus, I will close this item. Most likely it has been fixed during the last months. Thanks and sorry for being late.

**Comment by Pieter-Veenstra** [comment]
Hi PaolaPia,
I just tried this again with the December release and I'm still getting the problem.

When I get a template the welcome page file ( the .aspx file itself) doesn't seem to be exported). When I manually create testpage.aspx in the same folder as my .xml template file then all is working as expected.

**Comment by PaoloPia** [comment]
Uhm! Interesting ... I just tried with SPO and it worked. Are you on-premises or in SPO? Can you share the code or PoSH arguments that you are using? Thx.

**Comment by Pieter-Veenstra** [comment]
Ok, The steps are:

1. create a site
2. create a new page called testpage (testpage.aspx)
3. set the welcome page to a new page testpage.aspx
4. get the provisioning template 
**Get-PnPProvisioningTemplate -out c:\temp\testpage.xml**
5. create a new site ( at the url test)
6. apply the template to the new site.
**Apply-PnPProvisioningTemplate -web test -path c:\temp\testpage.xml**

if I create a text file called testpage.aspx in the same folder as the testpage.xml file. Even if it is just any odd text file without valid aspx content, then the apply command succeeds.

@PaoloPia when you run the Get- do you get an .aspx file in the output folder?

**Comment by PaoloPia** [comment]
I tried renaming an already existing file, not creating a new one. When I export the template I don't get the .ASPX file in the folder, but I just have the <pnp:Page /> item in the XML. Nevertheless, the page gets created in the target site.

**Comment by Pieter-Veenstra** [comment]
Hi @PaoloPia ,

I think this doesn't work for < pnp:Files>:

 < pnp:Files>
        < pnp:File Src="testpage.aspx" Folder="{site}/Pages" Overwrite="true">
          < pnp:Properties>
            < pnp:Property Key="ContentTypeId" Value="{contenttypeid:Project Page}" />
            < pnp:Property Key="Title" Value="testpage" />
            < pnp:Property Key="PublishingContact" Value="testuser@mytenant.onmicrosoft.com" />
            < pnp:Property Key="PublishingPageLayout" Value="{masterpagecatalog}/ProjectPage.aspx, Basic Project Page" />
            < pnp:Property Key="PublishingIsFurlPage" Value="False" />
            < pnp:Property Key="RobotsNoIndex" Value="False" />
            < pnp:Property Key="TaskStatus" Value="Not Started" />
            < pnp:Property Key="BSN" Value="Microsoft.SharePoint.Client.FieldLookupValue" />
            < pnp:Property Key="_ListSchemaVersion" Value="132" />
            < pnp:Property Key="_Dirty" Value="0" />
            < pnp:Property Key="_Parsable" Value="1" />
          < /pnp:Properties>
        < /pnp:File>
      </pnp:Files>

**Comment by PaoloPia** [comment]
I just tried using a wiki page (instead of a webpart page) and still works. Are you in SPO or on-premises?
The file doesn't get created in the folder, but the home page content (and the new file) still gets created on target.

**Comment by Pieter-Veenstra** [comment]
SPO

**Comment by PaoloPia** [comment]
I'm sorry but I cannot really reproduce it ... most likely I need much more details ... :-( eventually can you share the template? Thanks.

**Comment by PaoloPia** [comment]
Pieter, in the worst case ... we can make a short S4B call to figure out what's wrong ...

**Comment by erwinvanhunen** [comment]
@PieterVeenstra the content type and pagelayout for the page (Project Page), is that one included in the template?

**Comment by Pieter-Veenstra** [comment]
Hi @erwinvanhunen,

Just to get some more details into this issue.

I've got a site collection with the Wiki Publishing template.

Then I've got two subsites test and test2

**$cred = $null
if ($cred  -eq $null)
{
    $cred = Get-Credential -Message "Please supply password" -UserName "user@tenant.onmicrosoft.com"
    Connect-PnPOnline -Url https://tenant.sharepoint.com/sites/pieter -Credentials $cred
}
Get-PnPProvisioningTemplate -web test -out c:\temp\testagainpage.xml
Apply-PnPProvisioningTemplate -web test2 -path c:\temp\testagainpage.xml**


This now gives me the following xml:

https://pietersveenstra.files.wordpress.com/2017/01/testagainpage-xml.docx
(please rename this file to .xml)

**Comment by Pieter-Veenstra** [comment]
Hi @erwinvanhunen, @PaoloPia ,

The PowerShell script is falling over in:

U:\Git\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\Providers\Xml\XMLPnPSchemaV201605Formatter.cs

line 1527:

 result.Navigation.GlobalNavigation.StructuralNavigation.NavigationNodes.AddRange(
                        from n in source.Navigation.GlobalNavigation.StructuralNavigation.NavigationNode
                        select n.FromSchemaNavigationNodeToModelNavigationNodeV201605()
                        );


Stack trace: 


"   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)\r\n   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaV201605Formatter.ToProvisioningTemplate(Stream template, String identifier)\r\n   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaFormatter.ToProvisioningTemplate(Stream template, String identifier)\r\n   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.GetTemplate(String uri, String identifier, ITemplateFormatter formatter, ITemplateProviderExtension[] extensions)\r\n   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.GetTemplate(String uri, ITemplateProviderExtension[] extensions)\r\n   at SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate.ExecuteCmdlet()\r\n   at SharePointPnP.PowerShell.Commands.SPOCmdlet.ProcessRecord()"

**Comment by erwinvanhunen** [comment]
Hi Pieter,

While investigating your issue we discovered a bug in the engine, that we fixed with PR #933, which we think might solve this issue. Would it be possible for you to test with the latest dev branch? There is still the issue with the navigation node, which I noticed, and I'm working on a fix for that too. Temporarily remove the navigation node from your template or specify -ExcludeHandlers Navigation in the cmdlet.

**Comment by Pieter-Veenstra** [comment]
Hi Erwin,

I've just checked it in the latest dev branch. 

The following lines have now moved down to line: 1530

**result.Navigation.GlobalNavigation.StructuralNavigation.NavigationNodes.AddRange(
from n in source.Navigation.GlobalNavigation.StructuralNavigation.NavigationNode
select n.FromSchemaNavigationNodeToModelNavigationNodeV201605()
);**

as I step through the code I can see the NavigationNodes property in **result.Navigation.GlobalNavigation.StructuralNavigation.NavigationNodes** get being called. Then after that when I hover over **source.Navigation.GlobalNavigation.StructuralNavigation.NavigationNode** I can see that NavigationNode is set to null. 

Should your if that you have just added include
**source.Navigation.GlobalNavigation.StructuralNavigation.NavigationNode !=null** rather than 
**source.Navigation.GlobalNavigation.StructuralNavigation**

**Comment by erwinvanhunen** [comment]
Hi Pieter,

We fixed the navigation issue (it has been merged by PR #937 ) It was related to the name of the termgroup, which was not tokenized (there was actually no token for it). We introduced a new token {sitecollectiontermsetid:<name>} for it, which will, at runtime, map correctly to the site collection termset. It is important that during extraction this termset is included in the template, so this is how I extracted the template (with the new tokenization in place):

Get-PnPProvisioningTemplate -Out test.xml -Handlers PageContents,Navigation,TermGroups -IncludeSiteCollectionTermGroup

The result is a template with only containing the homepage, the navigation element and the termsets that make up the navigation. When applying this template to a new empty publishing site all the artifacts come over and navigation is working.

Obviously you don't have to specify the handlers if you want to include everything, but it is important to specify the -IncludeSiteCollectionTermGroup parameter.

**Comment by Pieter-Veenstra** [comment]
Hi Erwin,

Thanks a lot. I will test try to test this tomorrow.

**Comment by triad-cdp** [comment]
Hi Erwin,

Ok, the Files issue seems to still be there in the latest release. At least I have a workaround for that one.

When I create the templates as .xml and I add a copy of the .aspx file in the template directory then all seems to be working.

**Comment by Pieter-Veenstra** [comment]
Hi Erwin,

Ok, the Files issue seems to still be there in the latest release. At least I have a workaround for that one.

When I create the templates as .xml and I add a copy of the .aspx file in the template directory then all seems to be working.

**Comment by Pieter-Veenstra** [comment]
@PaoloPia,
This morning I took some more time to look into this issue where the creation of pages is failing and I can't see how this could possibly work.

In ObjectFiles near line 75:

```
if (file.Overwrite)
                        {
                            scope.LogDebug(CoreResources.Provisioning_ObjectHandlers_Files_Uploading_and_overwriting_existing_file__0_, file.Src);
                            checkedOut = CheckOutIfNeeded(web, targetFile);

                            using (var stream = GetFileStream(template, file))
                            {
                                **targetFile = UploadFile(template, file, folder, stream);**
                            }
                        }
```

I've set my breakpoint and step through the code. The UploadFile is failing with the exception. Simply because Pages/page.aspx doesn't exist as a file. 

When you apply a template does the above code work?

**Comment by erwinvanhunen** [comment]
@PieterVeenstra if you export the template with -PersistBrandingFiles, does the file get created in your folder? (mostt likely in a subfolder called "Pages")

**Comment by Pieter-Veenstra** [comment]
Hi @erwinvanhunen,

That works! My pages are now exported. Should I always include -PersistBrandingFiles is this something new? I can't remember having to do this before.

**Comment by PaoloPia** [comment]
Hi Pieter,
It's great to see that now it works. I will close this issue. Feel free to drop me a message if you have any new feedback and I will be more than happy to re-open it and support you. Thank you.
