### ISSUE TITLE
Applying a provisioning template to a sub site fails - startIndex cannot be larger than length of string

### ISSUE THREAD

**Issue by tommykri** [SharePoint/PnP-Sites-Core#630]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[x] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
February 2016 Cumulative Update for SharePoint 2013
#### Expected or Desired Behavior

I expect to be able to apply a provisioning template to a sub site using nuget package SharePointPnPCore2013 version 2.5.1606.1
#### Observed Behavior

When applying a provisioning template to a sub site I get the following exception

`startIndex cannot be larger than length of string.\r\nParameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser..ctor(Web web, ProvisioningTemplate template)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
   at ApplyTemplateToSubSiteBug.Program.Main(String[] args) in c:\users\sp_admin.dev\documents\visual studio 2015\Projects\ApplyTemplateToSubSiteBug\ApplyTemplateToSubSiteBug\Program.cs:line 27`

It it failing on line 74 on https://github.com/OfficeDev/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs when trying to add a list url token from the root web.

I have only been able to test this on-premises but I guess the same will apply to SharePoint Online.
#### Steps to Reproduce

A console application is available here which can be run to reproduce:
https://github.com/tommykri/SubSiteProvisioningBug

**Comment by VesaJuvonen** [comment]
thx Tommy, any change you could share the template and asset files with some of the core team members, so that we can do easy repro. We can't seem to find the combination to get this reproduced, so having material to do that would be great. Zip using Yammer private messages would be one option.

**Comment by juasmith** [comment]
Seeing this issue as well.

**Comment by paulpascha** [comment]
Ran into this issue also in SharePoint Online. Immediately rolled back to may release because we had to move on. Tried reproducing in an empty project with june release but didn't succeed so far.

**Comment by tommykri** [comment]
It can be reproduced with this code in a console application
 ```csharp
var template = new ProvisioningTemplate();
using (ClientContext context = new ClientContext("http://sitecollectionurl/somesubweb"))
{
   context.Web.ApplyProvisioningTemplate(template);
}
```
Seems to be fixed by #625 and #631 is also related.

I'm unable to use the june release because of this and must stick with may release for now.

**Comment by erwinvanhunen** [comment]
Hi Tommy,

Thanks for reporting this. We are still investigating the cause. We merged PR #625 and tested that one but this does not fully solve the issue as reported in issue #631. Or rather, it introduced another issue. Unfortunately I'm not able to reproduce it on a SP2013 environment myself, both by applying to a subweb in the root site collection or by applying the template to a subweb in a site collection located in a managed path. 

If you want/have time, please get the latest dev branch of PnP Core and test it with that one?

Thanks,

/Erwin

**Comment by erwinvanhunen** [comment]
One thing I notice that both you and the person reporting the issue in #631 are running the February 2016 CU of SharePoint...

**Comment by tommykri** [comment]
Hi

With the june release I'm able to reproduce this against SharePoint Online as well. I have updated my sample repo https://github.com/tommykri/SubSiteProvisioningBug to run against SharePoint Online.

#625 fixed the issue of getting an exception but I don't think the tokenparser resolves list url's from the root web correctly as the url's will be resolved as:
- "tyle Library"
- "catalogs/theme"
- "ists/SharePointHomeOrgLinks"

The beginning of the url will be stripped. Not sure how the url should be resolved as but shouldn't it be:

```
 _tokens.Add(new ListUrlToken(web, rootList.Title, rootList.RootFolder.ServerRelativeUrl));
```

 So the url's will be resolved as:
- "/style Library"
- "/_catalogs/theme"
- "/lists/SharePointHomeOrgLinks"

**Comment by SchauDK** [comment]
@tommykri #625 isn't included in the June release. It just got merged to the Dev branch yesterday.

**Comment by tommykri** [comment]
Yes I know but tested that I didn't got an exception with the Dev branch :)

**Comment by juasmith** [comment]
We are on June 15 CU.

**Comment by VesaJuvonen** [comment]
#625 is now released also as updated Nuget package with a version of 2.5.1606.2 for SP Online, SP2016 and for SP2013. This should fix this reported issue cross different environments. Going to close this and let's re-open if needed.

**Comment by bturkenburg** [comment]
@VesaJuvonen I think the issue is not yet solved... I'm getting the following error, after updating the latest Office Dev PnP PowerShell commands (June 2016 Intermediate Release 2):

_Apply-SPOProvisioningTemplate : The property or field 'ServerRelativeUrl' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested._

**Comment by erwinvanhunen** [comment]
@bturkenburg straight after you received that error message in PowerShell, can you enter the following line in PowerShell and post the results here? Thanks!

```powershell
$error[0].Exception.Stacktrace
```

**Comment by bturkenburg** [comment]
$error[0].Exception.Stacktrace
   at Microsoft.SharePoint.Client.ClientObject.CheckUninitializedProperty(String propName)
   at Microsoft.SharePoint.Client.Web.get_ServerRelativeUrl()
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser..ctor(Web web, ProvisioningTemplate template)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template,
 ProvisioningTemplateApplyingInformation provisioningInfo)
   at SharePointPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate.ExecuteCmdlet()
   at SharePointPnP.PowerShell.Commands.SPOCmdlet.ProcessRecord()

**Comment by erwinvanhunen** [comment]
Thank you, I'll have a look.

**Comment by erwinvanhunen** [comment]
I need a bit more information: On-Prem or O365? If On-Prem, what CU version?

**Comment by bturkenburg** [comment]
Hi Erwin, it's an On-Prem environment, with May 2016 CU. I think we need an extra line between line 80 and 81, with rootWeb.EnsureProperties(w => w.ServerRelativeUrl);

**Comment by erwinvanhunen** [comment]
Indeed. It seems that on-prem and O365 behave differently there. I'll add the line and merge it.

**Comment by erwinvanhunen** [comment]
Merged via PR #635

**Comment by PaoloPia** [comment]
Hi guys,
Looks like now this issue is fixed. Thus, I will close this item. In case of any further need, just let me know. Thanks.

**Comment by jansenbe** [comment]
**internal testing feedback:**
Source: Site collection test
- Download template from SiteA
- Created SiteB site collection

Successful:
- Provisioned template into SiteB successfully

Source: sub site test
- Download template from SiteA\Sub1
- Created SiteB\Sub1 sub site

Successful:
- Provisioned template into SiteB\Sub1 successfully
